USE lolmatchups;
INSERT INTO champion VALUES 
(113,"Sejuani","the Winter's Wrath","ChampionImages/Sejuani_Square_0.png"),
(126,"Jayce","the Defender of Tomorrow","ChampionImages/Jayce_Square_0.png"),
(117,"Lulu","the Fae Sorceress","ChampionImages/Lulu_Square_0.png"),
(12,"Alistar","the Minotaur","ChampionImages/Alistar_Square_0.png"),
(54,"Malphite","Shard of the Monolith","ChampionImages/Malphite_Square_0.png"),
(86,"Garen","The Might of Demacia","ChampionImages/Garen_Square_0.png"),
(51,"Caitlyn","the Sheriff of Piltover","ChampionImages/Caitlyn_Square_0.png"),
(90,"Malzahar","the Prophet of the Void","ChampionImages/Malzahar_Square_0.png"),
(14,"Sion","The Undead Juggernaut","ChampionImages/Sion_Square_0.png"),
(201,"Braum","the Heart of the Freljord","ChampionImages/Braum_Square_0.png"),
(72,"Skarner","the Crystal Vanguard","ChampionImages/Skarner_Square_0.png"),
(2,"Olaf","the Berserker","ChampionImages/Olaf_Square_0.png"),
(121,"Khazix","the Voidreaver","ChampionImages/Khazix_Square_0.png"),
(114,"Fiora","the Grand Duelist","ChampionImages/Fiora_Square_0.png"),
(55,"Katarina","the Sinister Blade","ChampionImages/Katarina_Square_0.png"),
(106,"Volibear","the Thunder's Roar","ChampionImages/Volibear_Square_0.png"),
(84,"Akali","the Fist of Shadow","ChampionImages/Akali_Square_0.png"),
(25,"Morgana","Fallen Angel","ChampionImages/Morgana_Square_0.png"),
(11,"MasterYi","the Wuju Bladesman","ChampionImages/MasterYi_Square_0.png"),
(21,"MissFortune","the Bounty Hunter","ChampionImages/MissFortune_Square_0.png"),
(60,"Elise","The Spider Queen","ChampionImages/Elise_Square_0.png"),
(412,"Thresh","the Chain Warden","ChampionImages/Thresh_Square_0.png"),
(76,"Nidalee","the Bestial Huntress","ChampionImages/Nidalee_Square_0.png"),
(59,"JarvanIV","the Exemplar of Demacia","ChampionImages/JarvanIV_Square_0.png"),
(1,"Annie","the Dark Child","ChampionImages/Annie_Square_0.png"),
(48,"Trundle","the Troll King","ChampionImages/Trundle_Square_0.png"),
(236,"Lucian","the Purifier","ChampionImages/Lucian_Square_0.png"),
(4,"TwistedFate","the Card Master","ChampionImages/TwistedFate_Square_0.png"),
(98,"Shen","Eye of Twilight","ChampionImages/Shen_Square_0.png"),
(268,"Azir","the Emperor of the Sands","ChampionImages/Azir_Square_0.png"),
(40,"Janna","the Storm's Fury","ChampionImages/Janna_Square_0.png"),
(30,"Karthus","the Deathsinger","ChampionImages/Karthus_Square_0.png"),
(24,"Jax","Grandmaster at Arms","ChampionImages/Jax_Square_0.png"),
(131,"Diana","Scorn of the Moon","ChampionImages/Diana_Square_0.png"),
(69,"Cassiopeia","the Serpent's Embrace","ChampionImages/Cassiopeia_Square_0.png"),
(267,"Nami","the Tidecaller","ChampionImages/Nami_Square_0.png"),
(127,"Lissandra","the Ice Witch","ChampionImages/Lissandra_Square_0.png"),
(3,"Galio","the Sentinel's Sorrow","ChampionImages/Galio_Square_0.png"),
(432,"Bard","the Wandering Caretaker","ChampionImages/Bard_Square_0.png"),
(154,"Zac","the Secret Weapon","ChampionImages/Zac_Square_0.png"),
(119,"Draven","the Glorious Executioner","ChampionImages/Draven_Square_0.png"),
(115,"Ziggs","the Hexplosives Expert","ChampionImages/Ziggs_Square_0.png"),
(89,"Leona","the Radiant Dawn","ChampionImages/Leona_Square_0.png"),
(22,"Ashe","the Frost Archer","ChampionImages/Ashe_Square_0.png"),
(161,"Velkoz","the Eye of the Void","ChampionImages/Velkoz_Square_0.png"),
(56,"Nocturne","the Eternal Nightmare","ChampionImages/Nocturne_Square_0.png"),
(19,"Warwick","the Blood Hunter","ChampionImages/Warwick_Square_0.png"),
(13,"Ryze","the Rogue Mage","ChampionImages/Ryze_Square_0.png"),
(92,"Riven","the Exile","ChampionImages/Riven_Square_0.png"),
(120,"Hecarim","the Shadow of War","ChampionImages/Hecarim_Square_0.png"),
(266,"Aatrox","the Darkin Blade","ChampionImages/Aatrox_Square_0.png"),
(36,"DrMundo","the Madman of Zaun","ChampionImages/DrMundo_Square_0.png"),
(143,"Zyra","Rise of the Thorns","ChampionImages/Zyra_Square_0.png"),
(85,"Kennen","the Heart of the Tempest","ChampionImages/Kennen_Square_0.png"),
(96,"KogMaw","the Mouth of the Abyss","ChampionImages/KogMaw_Square_0.png"),
(68,"Rumble","the Mechanized Menace","ChampionImages/Rumble_Square_0.png"),
(41,"Gangplank","the Saltwater Scourge","ChampionImages/Gangplank_Square_0.png"),
(112,"Viktor","the Machine Herald","ChampionImages/Viktor_Square_0.png"),
(62,"MonkeyKing","the Monkey King","ChampionImages/MonkeyKing_Square_0.png"),
(8,"Vladimir","the Crimson Reaper","ChampionImages/Vladimir_Square_0.png"),
(37,"Sona","Maven of the Strings","ChampionImages/Sona_Square_0.png"),
(238,"Zed","the Master of Shadows","ChampionImages/Zed_Square_0.png"),
(16,"Soraka","the Starchild","ChampionImages/Soraka_Square_0.png"),
(39,"Irelia","the Will of the Blades","ChampionImages/Irelia_Square_0.png"),
(102,"Shyvana","the Half-Dragon","ChampionImages/Shyvana_Square_0.png"),
(27,"Singed","the Mad Chemist","ChampionImages/Singed_Square_0.png"),
(254,"Vi","the Piltover Enforcer","ChampionImages/Vi_Square_0.png"),
(77,"Udyr","the Spirit Walker","ChampionImages/Udyr_Square_0.png"),
(43,"Karma","the Enlightened One","ChampionImages/Karma_Square_0.png"),
(110,"Varus","the Arrow of Retribution","ChampionImages/Varus_Square_0.png"),
(9,"FiddleSticks","the Harbinger of Doom","ChampionImages/FiddleSticks_Square_0.png"),
(28,"Evelynn","the Widowmaker","ChampionImages/Evelynn_Square_0.png"),
(31,"Chogath","the Terror of the Void","ChampionImages/Chogath_Square_0.png"),
(133,"Quinn","Demacia's Wings","ChampionImages/Quinn_Square_0.png"),
(57,"Maokai","the Twisted Treant","ChampionImages/Maokai_Square_0.png"),
(75,"Nasus","the Curator of the Sands","ChampionImages/Nasus_Square_0.png"),
(67,"Vayne","the Night Hunter","ChampionImages/Vayne_Square_0.png"),
(33,"Rammus","the Armordillo","ChampionImages/Rammus_Square_0.png"),
(45,"Veigar","the Tiny Master of Evil","ChampionImages/Veigar_Square_0.png"),
(111,"Nautilus","the Titan of the Depths","ChampionImages/Nautilus_Square_0.png"),
(34,"Anivia","the Cryophoenix","ChampionImages/Anivia_Square_0.png"),
(63,"Brand","the Burning Vengeance","ChampionImages/Brand_Square_0.png"),
(20,"Nunu","the Yeti Rider","ChampionImages/Nunu_Square_0.png"),
(58,"Renekton","the Butcher of the Sands","ChampionImages/Renekton_Square_0.png"),
(23,"Tryndamere","the Barbarian King","ChampionImages/Tryndamere_Square_0.png"),
(421,"RekSai","the Void Burrower","ChampionImages/RekSai_Square_0.png"),
(105,"Fizz","the Tidal Trickster","ChampionImages/Fizz_Square_0.png"),
(122,"Darius","the Hand of Noxus","ChampionImages/Darius_Square_0.png"),
(150,"Gnar","the Missing Link","ChampionImages/Gnar_Square_0.png"),
(107,"Rengar","the Pridestalker","ChampionImages/Rengar_Square_0.png"),
(134,"Syndra","the Dark Sovereign","ChampionImages/Syndra_Square_0.png"),
(61,"Orianna","the Lady of Clockwork","ChampionImages/Orianna_Square_0.png"),
(7,"Leblanc","the Deceiver","ChampionImages/Leblanc_Square_0.png"),
(50,"Swain","the Master Tactician","ChampionImages/Swain_Square_0.png"),
(222,"Jinx","the Loose Cannon","ChampionImages/Jinx_Square_0.png"),
(38,"Kassadin","the Void Walker","ChampionImages/Kassadin_Square_0.png"),
(80,"Pantheon","the Artisan of War","ChampionImages/Pantheon_Square_0.png"),
(26,"Zilean","the Chronokeeper","ChampionImages/Zilean_Square_0.png"),
(81,"Ezreal","the Prodigal Explorer","ChampionImages/Ezreal_Square_0.png"),
(429,"Kalista","the Spear of Vengeance","ChampionImages/Kalista_Square_0.png"),
(157,"Yasuo","the Unforgiven","ChampionImages/Yasuo_Square_0.png"),
(29,"Twitch","the Plague Rat","ChampionImages/Twitch_Square_0.png"),
(18,"Tristana","the Yordle Gunner","ChampionImages/Tristana_Square_0.png"),
(82,"Mordekaiser","the Master of Metal","ChampionImages/Mordekaiser_Square_0.png"),
(101,"Xerath","the Magus Ascendant","ChampionImages/Xerath_Square_0.png"),
(78,"Poppy","the Iron Ambassador","ChampionImages/Poppy_Square_0.png"),
(103,"Ahri","the Nine-Tailed Fox","ChampionImages/Ahri_Square_0.png"),
(17,"Teemo","the Swift Scout","ChampionImages/Teemo_Square_0.png"),
(83,"Yorick","the Gravedigger","ChampionImages/Yorick_Square_0.png"),
(99,"Lux","the Lady of Luminosity","ChampionImages/Lux_Square_0.png"),
(79,"Gragas","the Rabble Rouser","ChampionImages/Gragas_Square_0.png"),
(5,"XinZhao","the Seneschal of Demacia","ChampionImages/XinZhao_Square_0.png"),
(74,"Heimerdinger","the Revered Inventor","ChampionImages/Heimerdinger_Square_0.png"),
(104,"Graves","the Outlaw","ChampionImages/Graves_Square_0.png"),
(64,"LeeSin","the Blind Monk","ChampionImages/LeeSin_Square_0.png"),
(91,"Talon","the Blade's Shadow","ChampionImages/Talon_Square_0.png"),
(42,"Corki","the Daring Bombardier","ChampionImages/Corki_Square_0.png"),
(32,"Amumu","the Sad Mummy","ChampionImages/Amumu_Square_0.png"),
(35,"Shaco","the Demon Jester","ChampionImages/Shaco_Square_0.png"),
(15,"Sivir","the Battle Mistress","ChampionImages/Sivir_Square_0.png"),
(6,"Urgot","the Headsman's Pride","ChampionImages/Urgot_Square_0.png"),
(10,"Kayle","The Judicator","ChampionImages/Kayle_Square_0.png"),
(44,"Taric","the Gem Knight","ChampionImages/Taric_Square_0.png"),
(53,"Blitzcrank","the Great Steam Golem","ChampionImages/Blitzcrank_Square_0.png");